import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by Leewonno',
}

export default async function RootLayout({ children }: {
  children: React.ReactNode
}) {
  const res = await fetch('http://localhost:9999/topics');
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map((topic:any, index)=>{
            return(
              <li key={index}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            )
          })}
        </ol>
        {children}
        <ul>
          <li><Link href='/create'>Create</Link></li>
          <li><Link href='/update/1'>Uptate</Link></li>
          <li><input type='button' value='delete' /></li>
        </ul>
      </body>
    </html>
  )
}
