import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import { Control } from './Control'

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by Leewonno',
}


export default async function RootLayout({ children }: {
  children: React.ReactNode
}) {
  // revalidate : 0 // 캐시 유지 시간을 0초로 // 캐시를 이용하지 않겠다
  // {next:{revalidate:0}} or {cache:'no-store'}
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache:'no-store'});
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map((topic:any, index:number)=>{
            return(
              <li key={index}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            )
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
